### ISSUE TITLE
result in citeseer and pubmed

### ISSUE THREAD

**Issue by zhenshuozhang** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#1]
hi, I can't get the same result in the paper of dataset citeseer (around 72) and pubmed (around 80) in the mannual version code. Can you  share more details?

**Comment by zyzisastudyreallyhardguy** [comment]
Hi dusur, 

Thank you very much for your interest in our work. The implementation details you require are shown below:

**For PubMed, you could try running the following command:**
python execute.py --dataset 'pubmed' --np_epochs 500 --classifier_epochs 250 --hid_units 1024

**For CiteSeer, you could try running the following command:**
python execute.py --dataset 'citeseer' --classifier_epochs 80 --np_epochs 100 --lr 0.0005 --hid_units 1536
Please be aware that for CiteSeer, you only need the original embedding 'or_embeds' for testing (i.e., no need for the embedding reinforcement)

We will update our code later to include these two datasets.

Best Regards,
Yizhen Zheng

**Comment by zhenshuozhang** [comment]
> 

thx for your reply
