### ISSUE TITLE
Some Questions about Table 2

### ISSUE THREAD

**Issue by YuxinTang0315** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#2]
Why do I find in the experiment that the average value of the relu/lrelu/plrelu function is less than 0.1, while the average value of the sigmoid function is 0.5?

**Comment by zyzisastudyreallyhardguy** [comment]
Hi Tang,

The constant summary vector phenomenon occurred in DGI's originally released code.
You can easily reproduce the result by following the steps:

1. Download the DGI code from DGI's github repo https://github.com/PetarV-/DGI
2. print the DGI/models/dgi.py variable c (the summary vector) as shown below:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/75228223/204078458-b1b25459-6ef5-4b39-b351-67edf12411b0.png">
3.If you want to try other activation functions, you can set it in the execute.py file of DGI's code.



Warmest Regards,
YIZHEN ZHENG

**Comment by YuxinTang0315** [comment]
Sorry, I don't have described my problem clearly. I know how to use this code and I have tried sigmoid/relu/prelu/lrelu function. But the results I got is different from the Table 2 in your paper. In my experiment, using the sigmoid function, the eigenvector c of the graph is 0.5, and using the relu/prelu/lrelu function, the eigenvector c of the graph is less than 0.1.

**Comment by zyzisastudyreallyhardguy** [comment]
Hi Tang,

Sorry for the late reply. On my end, I have validated the result in the table is correct. 

Here is the result when I use sigmoid as the activation function for the GNN encoder. (Directly print out the summary vector in DGI's officially released code)

<img width="879" alt="image" src="https://user-images.githubusercontent.com/75228223/205444901-9a3c6e33-ac99-4648-8839-37b5b0ea16de.png">

This is the result I use sigmoid as the activation function for the GNN encoder. 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/75228223/205445087-4b9a59cc-77b6-44f2-86d2-45d28e4ecd3f.png">

To achieve the result with sigmoid activation, you only need to modify the gcn.py code in the layers folder
<img width="568" alt="image" src="https://user-images.githubusercontent.com/75228223/205445126-3a039b12-9f36-4b3c-b10d-02e0c5e210ce.png">

Best Regards,
YIZHEN ZHENG
