### ISSUE TITLE
manual_version for Photo and Computers

### ISSUE THREAD

**Issue by agoyang** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#3]
Hi Yizhen, thanks for sharing your code! 
I've tested the execute.py in manual_version for Cora, CiteSeer and Pubmed, it works perfectly fine. Then I use pyg to generate other datasets, the result is good for Coauthor-cs, but both Photo and Computers perform poorly (accuracy lower than 70).
Do you have any suggestions for this two datasets or script for them?
Best wishes

**Comment by zyzisastudyreallyhardguy** [comment]
Dear agoyang,

Sorry for the late reply. I was on leave recently. I have already updated the code to include these two datasets and the experiment setting is included in the readme file.

Please let me know if there is any other issue.

Best Regards,
Yizhen Zheng

**Comment by agoyang** [comment]
Dear Yizhen,

Thanks for your reply! I have tested all datasets, and the new script works perfect.

Best wishes
