### ISSUE TITLE
How can i get the code of GGD on Paper100M Dataset?

### ISSUE THREAD

**Issue by LingyuanMeng17** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#4]
Congratulations on your NeurIPS paper. It is a great work. Could you please realse the code of GGD on paper100M dataset , how can i get them?

**Comment by zyzisastudyreallyhardguy** [comment]
Dear Meng,

The code of GGD on paper100M dataset is very close to the code for Ogbn-product, which has been released in the github repo. You could try running paper100M with it.

Best Regards,
YIZHEN ZHENG
