### ISSUE TITLE
Method for measuring memory consumption.

### ISSUE THREAD

**Issue by agoyang** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#5]
Dear Yizhen,
I'm comparing memory consumption of GCL models these days. It seems like your results in Table 7 are closer to the result from nvidia-smi. When I use torch.cuda.max_memory_allocated(), GGD takes less than 200MB on Cora. So I think it's better to tell you that your model is even more scalable than you think.
Best wishes.

**Comment by zyzisastudyreallyhardguy** [comment]
Thank you for letting me know!

Best Regards,
YIZHEN ZHENG
