### ISSUE TITLE
A question about Eq. (1)

### ISSUE THREAD

**Issue by Thetwotwo** [zyzisastudyreallyhardguy/Graph-Group-Discrimination#6]

**Comment by Thetwotwo** [comment]
您好，有幸看到您的文章，深受启发。请问一下公式(1)中第一步到第二步的推导中，sigmoid函数是怎么消去的呢？

**Comment by zyzisastudyreallyhardguy** [comment]
Thetwotwo同学您好, 在DGI的源代码中，在得到summary vector之前需要经过一层sigmoid layer。经过这层sigmoid layer后，summary vector中的值都会趋向于同一个值。这个是这篇文章最主要的发现。

既然summary vector在经过sigmoid layer后都是趋向于同一个值，那么是不是summary vector根本就没在model training的过程中发挥任何作用呢? 因此从Equation 1的三步推导中，我们直接把summary vector直接去掉了(设为全1向量)。这么做就相当于直接对z_i向量中的所有值求和。最后这个公式可以进一步推导成一个binary cross entropy loss。

因为在group discrimination的自监督学习策略中，summary vector被去掉了(设为全1向量)，自然我们也就不需要sigmoid layer了。

Best,
YIZHEN ZHENG

**Comment by Thetwotwo** [comment]
在表格1中，显示GGD(256)经过1个epoch的训练便能得到70.3的精度。然而，我试了下，即使模型不经过训练（即0 epoch），利用初始化的权重，仍然能得到70.3左右的结果。感觉表1中不错的效果受益于良好的初始化，而不是方法本身的快速收敛性。

**Comment by zyzisastudyreallyhardguy** [comment]
您好 同学 代码中显示是0epoch 其实这是第一个epoch 我们计数把0当作了1

**Comment by Thetwotwo** [comment]
I like this paper. Anyway, it's still a great job. Good luck with your scientific research!

**Comment by zyzisastudyreallyhardguy** [comment]
Thank you very much for your appreciation!
